export enum UNIT_TYPES {
    VILLA = 'villa',
    WORKSHOP = 'workshop',
    OFFICE = 'office',
    MINE = 'mine',
    SHOP = 'shop',
    WAREHOUSE = 'warehouse',
    ANIMAL_FARM = 'animalfarm',
    MILL = 'mill',
    SAW_MILL = 'sawmill',
    FARM = 'farm',
    LAB = 'lab',
    ORCHARD = 'orchard',
    SEAPORT = 'seaport',
    FISHING_BASE = 'fishingbase',
    SERVICE_LIGHT = 'service_light',
    MEDICINE = 'medicine',
    RESTAURANT = 'restaurant',
    POWER = 'power',
    FUEL = 'fuel',
    REPAIR = 'repair',
    EDUCATIONAL = 'educational',
    NETWORK = 'network',
    IT = 'it'
}
